[pytest]
addopts = -q --tracing=retain-on-failure --screenshot=only-on-failure
pythonpath = .
testpaths = tests
base_url = https://demo.playwright.dev/todomvc/
markers =
    smoke: critical fast tests
    regression: full regression test set
    negative: tests for invalid input and errors
    api: API tests
    ui: browser user interface test
    selenium: UI tests using Selenium WebDriver
